import { randomUUID } from 'node:crypto';
import { Prisma } from '../generated/prisma/client.js';
import { prisma } from '../db/prisma.js';
import { adminAccess } from './admin.service.js';

const aliases:Record<string,string>={'महुआ':'mahua','महुवा':'mahua','लाख':'lac','लाह':'lac','सोहराय':'sohrai','हस्तशिल्प':'handicraft'};
export const normalizeQuery=(value:string)=>{const clean=value.trim().toLowerCase().replace(/\s+/g,' ');return aliases[clean]||clean};
const since=(days:number)=>new Date(Date.now()-Math.min(365,Math.max(1,days))*86400000);
const lastRun=()=>prisma.analyticsAggregationRun.findFirst({where:{status:'SUCCEEDED'},orderBy:{completedAt:'desc'},select:{completedAt:true}});

export async function aggregateAnalytics(){const day=new Date();day.setUTCHours(0,0,0,0);const runKey=`daily:${day.toISOString().slice(0,10)}`;const run=await prisma.analyticsAggregationRun.upsert({where:{runKey},update:{status:'RUNNING',startedAt:new Date(),error:null},create:{runKey,status:'RUNNING'}});try{const products=await prisma.product.findMany({include:{variants:{include:{orderItems:{where:{vendorOrder:{createdAt:{gte:day}}}}}},analyticsEvents:{where:{createdAt:{gte:day}}}}});let rows=0;for(const product of products){const count=(t:string)=>product.analyticsEvents.filter(e=>e.type===t).length;const items=product.variants.flatMap(v=>v.orderItems);await prisma.productDailyAggregate.upsert({where:{productId_date:{productId:product.id,date:day}},update:{impressions:count('IMPRESSION'),views:count('VIEW'),cartAdds:count('ADD_TO_CART'),checkouts:count('CHECKOUT_STARTED'),purchases:items.length,unitsSold:items.reduce((s,i)=>s+i.quantity,0),revenue:items.reduce((s,i)=>s.plus(i.lineTotal),new Prisma.Decimal(0))},create:{productId:product.id,date:day,impressions:count('IMPRESSION'),views:count('VIEW'),cartAdds:count('ADD_TO_CART'),checkouts:count('CHECKOUT_STARTED'),purchases:items.length,unitsSold:items.reduce((s,i)=>s+i.quantity,0),revenue:items.reduce((s,i)=>s.plus(i.lineTotal),new Prisma.Decimal(0))}});rows++;}await prisma.analyticsAggregationRun.update({where:{id:run.id},data:{status:'SUCCEEDED',completedAt:new Date(),rowsProcessed:rows}});return{runKey,rows};}catch(error){await prisma.analyticsAggregationRun.update({where:{id:run.id},data:{status:'FAILED',completedAt:new Date(),error:error instanceof Error?error.message:'Unknown aggregation error'}});throw error;}}

export async function searchInsights(userId:string,days=30){await adminAccess(userId,'analytics:read');const events=await prisma.productAnalyticsEvent.findMany({where:{createdAt:{gte:since(days)},searchQuery:{not:null}},include:{product:{select:{name:true,district:true}}}});const groups=new Map<string,{family:string;queries:Set<string>;impressions:number;clicks:number;carts:number;products:Set<string>;districts:Set<string>}>();for(const e of events){const family=normalizeQuery(e.searchQuery!);const g=groups.get(family)||{family,queries:new Set(),impressions:0,clicks:0,carts:0,products:new Set(),districts:new Set()};g.queries.add(e.searchQuery!);if(e.type==='IMPRESSION')g.impressions++;if(e.type==='SEARCH_CLICK')g.clicks++;if(e.type==='ADD_TO_CART')g.carts++;g.products.add(e.product.name);g.districts.add(e.product.district);groups.set(family,g);}return{snapshotAt:new Date(),lastAggregatedAt:(await lastRun())?.completedAt??null,items:[...groups.values()].map(g=>({queryFamily:g.family,queries:[...g.queries],impressions:g.impressions,clicks:g.clicks,cartAdds:g.carts,ctr:g.impressions?Number((g.clicks/g.impressions*100).toFixed(1)):0,resultProducts:g.products.size,districts:[...g.districts],state:g.clicks===0?'missed-demand':g.carts===0?'low-conversion':'converting',recommendation:g.clicks===0?'Create or improve products for this search.':g.carts===0?'Improve product title, image or pricing.':'Continue promoting matching products.'})).sort((a,b)=>b.impressions-a.impressions)};}

export async function inventoryIntelligence(userId:string){await adminAccess(userId,'analytics:read');const now=new Date();const variants=await prisma.productVariant.findMany({where:{isActive:true},include:{product:{include:{vendor:true,category:true}},orderItems:{where:{vendorOrder:{createdAt:{gte:since(90)}}},include:{vendorOrder:true}}}});const items=variants.map(v=>{const units=(days:number)=>v.orderItems.filter(i=>i.vendorOrder.createdAt>=since(days)).reduce((s,i)=>s+i.quantity,0);const u7=units(7),u30=units(30),u90=units(90);const velocity=(u7/7)*.5+(u30/30)*.3+(u90/90)*.2;const forecast7=Math.ceil(velocity*7),forecast30=Math.ceil(velocity*30),safety=Math.ceil(velocity*7),reorder=Math.max(0,forecast30+safety-v.stock),daysRemaining=velocity>0?Math.floor(v.stock/velocity):null;const observations=v.orderItems.length;const confidence=observations>=20?'HIGH':observations>=5?'MEDIUM':'LOW';return{variantId:v.id,productId:v.productId,product:v.product.name,vendor:v.product.vendor.businessName,category:v.product.category.name,district:v.product.district,label:v.label,sku:v.sku,price:Number(v.price),stock:v.stock,inputs:{units7:u7,units30:u30,units90:u90,weights:{days7:.5,days30:.3,days90:.2}},dailyVelocity:Number(velocity.toFixed(3)),forecast7,forecast30,recommendedReorder:reorder,daysRemaining,expectedStockoutAt:daysRemaining===null?null:new Date(now.getTime()+daysRemaining*86400000),potentialLostSales:Math.max(0,forecast30-v.stock)*Number(v.price),confidence,classification:velocity===0?'dead':daysRemaining!==null&&daysRemaining<=7?'critical':velocity<.15?'slow':'healthy',explanation:`Weighted daily demand: 50% of 7-day, 30% of 30-day and 20% of 90-day velocity; plus 7 days safety stock.`};});return{snapshotAt:now,lastAggregatedAt:(await lastRun())?.completedAt??null,items};}

export async function districtAnalytics(userId:string,days=30){await adminAccess(userId,'analytics:read');const products=await prisma.product.findMany({include:{analyticsEvents:{where:{createdAt:{gte:since(days)}}},variants:{include:{orderItems:{where:{vendorOrder:{createdAt:{gte:since(days)}}},include:{vendorOrder:true}}}}}});const map=new Map<string,{district:string;views:number;searchDemand:number;unitsSold:number;gmv:number;rto:number;orders:number}>();for(const p of products){const g=map.get(p.district)||{district:p.district,views:0,searchDemand:0,unitsSold:0,gmv:0,rto:0,orders:0};g.views+=p.analyticsEvents.filter(e=>e.type==='VIEW').length;g.searchDemand+=p.analyticsEvents.filter(e=>Boolean(e.searchQuery)).length;for(const i of p.variants.flatMap(v=>v.orderItems)){g.unitsSold+=i.quantity;g.gmv+=Number(i.lineTotal);g.orders++;if(i.vendorOrder.status==='RTO')g.rto++;}map.set(p.district,g);}return{snapshotAt:new Date(),lastAggregatedAt:(await lastRun())?.completedAt??null,items:[...map.values()].map(g=>({...g,conversion:g.views?Number((g.unitsSold/g.views*100).toFixed(1)):0,rtoRate:g.orders?Number((g.rto/g.orders*100).toFixed(1)):0}))};}

const safeCell=(v:unknown)=>{const text=String(v??'');const safe=/^[=+\-@]/.test(text)?`'${text}`:text;return `"${safe.replaceAll('"','""')}"`};
export async function productCsv(userId:string,days=30,q=''){await adminAccess(userId,'analytics:export');const {listProductAnalytics}=await import('./product-analytics.service.js');const rows=await listProductAnalytics(userId,{days,...(q?{q}:{})});const header=['Product','Vendor','Category','District','Views','Cart Adds','Units Sold','Conversion %','Revenue','Stock','Health Score','Health Band'];const csv=[header,...rows.map(r=>[r.name,r.vendor,r.category,r.district,r.views,r.cartAdds,r.purchases,r.conversionRate,r.revenue,r.stock,r.health.score,r.health.band])].map(row=>row.map(safeCell).join(',')).join('\r\n');await prisma.adminAuditLog.create({data:{actorId:userId,action:'PRODUCT_ANALYTICS_EXPORT',entityType:'AnalyticsExport',entityId:randomUUID(),permission:'analytics:export',metadata:{days,q,rowCount:rows.length}}});return{csv,rowCount:rows.length};}
