import { ProductEventType, Prisma } from '../generated/prisma/client.js';
import { prisma } from '../db/prisma.js';
import { ApiError } from '../utils/api-error.js';
import { adminAccess } from './admin.service.js';

export interface ProductEventInput { eventKey:string; type:ProductEventType; productId:string; variantId?:string; sessionId:string; district?:any; source?:string; searchQuery?:string; device?:string; quantity?:number; price?:number; }
export async function recordEvent(input:ProductEventInput){const product=await prisma.product.findFirst({where:{id:input.productId,isPublished:true},select:{id:true}});if(!product)throw new ApiError(404,'Published product was not found.','PRODUCT_NOT_FOUND');if(input.variantId){const variant=await prisma.productVariant.findFirst({where:{id:input.variantId,productId:input.productId},select:{id:true}});if(!variant)throw new ApiError(422,'Variant does not belong to this product.','INVALID_VARIANT');}return prisma.productAnalyticsEvent.upsert({where:{eventKey:input.eventKey},update:{},create:{...input,price:input.price===undefined?null:new Prisma.Decimal(input.price)}});}
const pct=(a:number,b:number)=>b?Number((a/b*100).toFixed(1)):0;
function health(product:any,views:number,carts:number,purchases:number,rto:number,delivered:number){const conversion=Math.min(25,Math.round(pct(purchases,views)*2.5));const content=[product.description?.length>=80,product.artisanStory?.length>=40,product.media.length>=2,Boolean(product.materials),Boolean(product.careInstructions)].filter(Boolean).length*3;const totalStock=product.variants.reduce((s:number,v:any)=>s+v.stock,0);const stock=totalStock===0?0:totalStock<5?7:15;const fulfilment=delivered+rto?Math.round(delivered/(delivered+rto)*20):10;const score=Math.min(100,conversion+content+stock+fulfilment+25);const recommendations:string[]=[];if(views>20&&carts/views<.05)recommendations.push('High views but low cart additions: improve cover image, price or value proposition.');if(totalStock<5)recommendations.push('Restock low or unavailable variants.');if(product.media.length<2)recommendations.push('Add at least two clear product photos.');if(!product.materials)recommendations.push('Add materials and authenticity details.');if(rto>delivered*.15)recommendations.push('RTO rate is high; review packaging and delivery expectations.');return{score,band:score>=80?'Healthy':score>=60?'Needs optimization':score>=40?'At risk':'Critical',recommendations};}
export async function listProductAnalytics(userId:string,input:{days?:number;q?:string}){await adminAccess(userId,'analytics:read');const days=Math.min(365,Math.max(1,input.days||30)),since=new Date(Date.now()-days*86400000);const products=await prisma.product.findMany({where:input.q?{name:{contains:input.q,mode:'insensitive'}}:{},include:{vendor:true,category:true,media:true,variants:{include:{orderItems:{where:{vendorOrder:{createdAt:{gte:since}}},include:{vendorOrder:true}}}},analyticsEvents:{where:{createdAt:{gte:since}}}}});return products.map(product=>{const count=(type:ProductEventType)=>product.analyticsEvents.filter(e=>e.type===type).length;const views=count('VIEW'),impressions=count('IMPRESSION'),cartAdds=count('ADD_TO_CART');const items=product.variants.flatMap(v=>v.orderItems);const purchases=items.reduce((s,i)=>s+i.quantity,0),revenue=items.reduce((s,i)=>s+Number(i.lineTotal),0),rto=items.filter(i=>i.vendorOrder.status==='RTO').length,delivered=items.filter(i=>i.vendorOrder.status==='DELIVERED').length;return{id:product.id,name:product.name,vendor:product.vendor.businessName,category:product.category.name,district:product.district,status:product.lifecycleStatus,impressions,views,cartAdds,purchases,revenue,clickThroughRate:pct(views,impressions),cartRate:pct(cartAdds,views),conversionRate:pct(purchases,views),stock:product.variants.reduce((s,v)=>s+v.stock,0),health:health(product,views,cartAdds,purchases,rto,delivered)};});}
export async function productAnalyticsDetail(userId:string,id:string,days=30){await adminAccess(userId,'analytics:read');const rows=await listProductAnalytics(userId,{days});const summary=rows.find(r=>r.id===id);if(!summary)throw new ApiError(404,'Product analytics was not found.','PRODUCT_NOT_FOUND');const since=new Date(Date.now()-days*86400000);const product=await prisma.product.findUnique({where:{id},include:{variants:true,analyticsEvents:{where:{createdAt:{gte:since}},orderBy:{createdAt:'asc'}}}});return{summary,product,funnel:{impressions:summary.impressions,views:summary.views,cartAdds:summary.cartAdds,purchases:summary.purchases},searchQueries:Object.entries(product!.analyticsEvents.reduce<Record<string,number>>((acc,event)=>{if(event.searchQuery)acc[event.searchQuery]=(acc[event.searchQuery]||0)+1;return acc;},{})).sort((a,b)=>b[1]-a[1]).slice(0,20)};}
