import { randomUUID } from 'node:crypto';
import { FulfillmentStatus, JharkhandDistrict, ModerationStatus, PayoutRequestStatus, VerificationStatus, WeeklyHaatDay } from '../generated/prisma/client.js';
import { env } from '../config/env.js';
import { prisma } from '../db/prisma.js';
import { ApiError } from '../utils/api-error.js';
import { money } from '../utils/money.js';

async function vendorFor(userId: string) { const vendor = await prisma.vendor.findUnique({ where: { ownerId: userId } }); if (!vendor || vendor.verificationStatus !== VerificationStatus.VERIFIED) throw new ApiError(403, 'A verified vendor account is required.', 'VENDOR_NOT_VERIFIED'); return vendor; }
export async function dashboard(userId: string) { const vendor = await vendorFor(userId); const [products, orders, ledgers, payoutRequests] = await Promise.all([prisma.product.findMany({ where: { vendorId: vendor.id }, include: { variants: true } }), prisma.vendorOrder.findMany({ where: { vendorId: vendor.id }, include: { items: true }, orderBy: { createdAt: 'desc' } }), prisma.walletLedger.findMany({ where: { vendorId: vendor.id }, orderBy: { createdAt: 'desc' } }), prisma.payoutRequest.findMany({ where: { vendorId: vendor.id }, orderBy: { requestedAt: 'desc' } })]); return { vendor, products, orders, ledgers, payoutRequests }; }
export async function createProduct(userId: string, input: { name: string; slug: string; description: string; artisanStory?: string; categoryId: string; district: JharkhandDistrict; weeklyHaatDay: WeeklyHaatDay; variants: { sku: string; label: string; price: number; stock: number }[] }) { const vendor = await vendorFor(userId); if (!input.variants.length) throw new ApiError(422, 'At least one variant is required.', 'VARIANT_REQUIRED'); const minPrice = Math.min(...input.variants.map((item) => item.price)); return prisma.product.create({ data: { vendorId: vendor.id, categoryId: input.categoryId, name: input.name, slug: input.slug, description: input.description, artisanStory: input.artisanStory ?? null, district: input.district, weeklyHaatDay: input.weeklyHaatDay, minPrice, isPublished: true, variants: { create: input.variants.map((item) => ({ ...item, lowStock: item.stock < env.LOW_STOCK_THRESHOLD })) } }, include: { variants: true } }); }
export async function updateStock(userId: string, variantId: string, stock: number) { const vendor = await vendorFor(userId); const variant = await prisma.productVariant.findFirst({ where: { id: variantId, product: { vendorId: vendor.id } } }); if (!variant) throw new ApiError(404, 'Variant was not found.', 'VARIANT_NOT_FOUND'); return prisma.productVariant.update({ where: { id: variantId }, data: { stock, lowStock: stock < env.LOW_STOCK_THRESHOLD, version: { increment: 1 } } }); }
const transitions: Record<FulfillmentStatus, FulfillmentStatus[]> = { PENDING: [FulfillmentStatus.PACKED, FulfillmentStatus.CANCELLED], PACKED: [FulfillmentStatus.SHIPPED, FulfillmentStatus.CANCELLED], SHIPPED: [FulfillmentStatus.DELIVERED, FulfillmentStatus.RTO], DELIVERED: [], RTO: [], CANCELLED: [] };
export async function transitionOrder(userId: string, id: string, status: FulfillmentStatus) { const vendor = await vendorFor(userId); const order = await prisma.vendorOrder.findFirst({ where: { id, vendorId: vendor.id } }); if (!order) throw new ApiError(404, 'Vendor order was not found.', 'VENDOR_ORDER_NOT_FOUND'); if (!transitions[order.status].includes(status)) throw new ApiError(409, `Cannot move order from ${order.status} to ${status}.`, 'INVALID_ORDER_TRANSITION'); return prisma.vendorOrder.update({ where: { id }, data: { status, ...(status === FulfillmentStatus.DELIVERED ? { deliveredAt: new Date() } : {}), statusLogs: { create: { status, actorUserId: userId, note: 'Updated by vendor.' } } }, include: { items: true, statusLogs: true } }); }
export async function shippingLabel(userId: string, id: string) { const vendor = await vendorFor(userId); const order = await prisma.vendorOrder.findFirst({ where: { id, vendorId: vendor.id }, include: { items: true, order: true } }); if (!order) throw new ApiError(404, 'Vendor order was not found.', 'VENDOR_ORDER_NOT_FOUND'); return { trackingId: order.trackingId, vendor: vendor.businessName, recipientName: order.order.recipientName, recipientMobile: order.order.recipientMobile, addressLine1: order.order.addressLine1, district: order.order.district, postalCode: order.order.postalCode, items: order.items }; }
export async function requestPayout(userId: string) { const vendor = await vendorFor(userId); const pending = await prisma.payoutRequest.findFirst({ where: { vendorId: vendor.id, status: { in: [PayoutRequestStatus.PENDING, PayoutRequestStatus.PROCESSING] } } }); if (pending) return pending; if (vendor.walletBalance.lessThanOrEqualTo(0)) throw new ApiError(422, 'No available wallet balance.', 'NO_PAYOUT_BALANCE'); return prisma.payoutRequest.create({ data: { vendorId: vendor.id, amount: money(vendor.walletBalance), reference: `PAY-${randomUUID()}` } }); }
export async function submitApplication(input: any) { const existing = await prisma.vendorApplication.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include: { documents: true } }); if (existing) return existing; const { msmeCertificate, ...data } = input; return prisma.vendorApplication.create({ data: { ...data, status: ModerationStatus.PENDING, documents: { create: [{ category: 'MSME', objectKey: msmeCertificate.objectKey, fileName: msmeCertificate.fileName, mimeType: msmeCertificate.mimeType, size: msmeCertificate.size }] } }, include: { documents: true } }); }
