export const kolhanSoapCategories = [
  { slug: 'clay-soaps', name: 'Clay Soaps', nameHi: 'क्ले साबुन', displayOrder: 10 },
  { slug: 'honey-soaps', name: 'Honey Soaps', nameHi: 'शहद वाले साबुन', displayOrder: 20 },
  { slug: 'goat-milk-soaps', name: 'Goat Milk Soaps', nameHi: 'बकरी के दूध वाले साबुन', displayOrder: 30 },
  { slug: 'herbal-soaps', name: 'Herbal Soaps', nameHi: 'हर्बल साबुन', displayOrder: 40 },
  { slug: 'botanical-soaps', name: 'Botanical Soaps', nameHi: 'बॉटनिकल साबुन', displayOrder: 50 },
  { slug: 'gift-sets', name: 'Gift Sets', nameHi: 'उपहार सेट', displayOrder: 60 },
  { slug: 'handmade-soaps', name: 'Handmade Soaps', nameHi: 'हस्तनिर्मित साबुन', displayOrder: 70 },
] as const;

export const kolhanSoapProducts = [
  {
    slug: 'kolhan-clay-soap',
    sku: 'KOLHAN-CLAY-SOAP-100G',
    name: 'Kolhan Clay Soap',
    description: 'A clay-rich handmade bar inspired by the earth of Kolhan.',
    categorySlug: 'clay-soaps',
    price: '100.00',
    label: '100g',
    initialStock: 0,
    initiallyPublished: false,
  },
  {
    slug: 'active-bamboo-charcoal-menthol-soap',
    sku: 'KOLHAN-CHARCOAL-MENTHOL-SOAP-100G',
    name: 'Active bamboo Charcoal & Menthol Soap',
    description: 'A refreshing handmade bar with active bamboo charcoal and menthol.',
    categorySlug: 'honey-soaps',
    price: '130.00',
    label: '100g',
    initialStock: 0,
    initiallyPublished: false,
  },
  {
    slug: 'goat-milk-soap',
    sku: 'KOLHAN-GOAT-MILK-SOAP-100G',
    name: 'Goat Milk Soap',
    description: 'A creamy handmade bar crafted with goat milk.',
    categorySlug: 'goat-milk-soaps',
    price: '110.00',
    label: '100g',
    initialStock: 0,
    initiallyPublished: false,
  },
  {
    slug: 'honey-goat-milk-soap',
    sku: 'KOLHAN-HONEY-GOAT-MILK-SOAP-100G',
    name: 'Honey Goat Milk Soap',
    description: 'A creamy handmade bar crafted with honey and goat milk.',
    categorySlug: 'honey-soaps',
    price: '110.00',
    label: '100g',
    initialStock: 0,
    initiallyPublished: false,
  },
  {
    slug: 'mix-clay-soap',
    sku: 'KOLHAN-MIX-CLAY-SOAP-100G',
    name: 'Mix Clay Soap',
    description: 'A premium handcrafted soap made with a distinctive blend of clays.',
    categorySlug: 'clay-soaps',
    price: '210.00',
    label: '100g',
    initialStock: 0,
    initiallyPublished: false,
  },
  {
    slug: 'kojic-coffee-soap',
    sku: 'KOLHAN-KOJIC-COFFEE-SOAP-100G',
    name: 'Kojic Coffee Soap',
    description: 'A coffee-infused handmade bar for daily use.',
    categorySlug: 'handmade-soaps',
    price: '140.00',
    label: '100g',
    initialStock: 0,
    initiallyPublished: false,
  },
] as const;

export const legacyMarketplaceCategorySlugs = [
  'forest-foods',
  'tribal-crafts',
  'handloom',
  'natural-wellness',
] as const;
