import type { RequestHandler } from 'express';
import { AdminTeamRole, FulfillmentStatus, ModerationStatus } from '../generated/prisma/client.js';
import * as admin from '../services/admin.service.js';
import * as adminCustomer from '../services/admin-customer.service.js';
import * as adminTransaction from '../services/admin-transaction.service.js';
import * as adminAudit from '../services/admin-audit.service.js';
import * as adminCoupon from '../services/admin-coupon.service.js';
import * as adminReview from '../services/admin-review.service.js';
import * as adminCategory from '../services/admin-category.service.js';
import * as adminHomepageVideo from '../services/admin-homepage-video.service.js';
import * as influencerCommission from '../services/influencer-commission.service.js';
import * as adminPayout from '../services/admin-payout.service.js';
import * as featuredEndorsement from '../services/featured-endorsement.service.js';

export const analytics: RequestHandler = async (req, res) => res.json({ data: await admin.analytics(req.auth!.userId, Number(req.query.months ?? 6)) });
export const haats: RequestHandler = async (req, res) => res.json({ data: await admin.listHaats(req.auth!.userId) });
export const saveHaat: RequestHandler = async (req, res) => res.status(req.params.id ? 200 : 201).json({ data: await admin.saveHaat(req.auth!.userId, req.params.id ? String(req.params.id) : undefined, req.body, req.requestId) });
export const toggleHaat: RequestHandler = async (req, res) => res.json({ data: await admin.toggleHaat(req.auth!.userId, String(req.params.id), req.body.enabled, req.requestId) });
export const liveHaat: RequestHandler = async (req, res) => res.status(201).json({ data: await admin.setLiveHaat(req.auth!.userId, String(req.params.id), new Date(req.body.liveUntil), req.requestId) });
export const categories: RequestHandler = async (req, res) => res.json({ data: await adminCategory.categories(req.auth!.userId) });
export const createCategory: RequestHandler = async (req, res) => res.status(201).json({ data: await adminCategory.createCategory(req.auth!.userId, req.requestId, req.body) });
export const updateCategory: RequestHandler = async (req, res) => res.json({ data: await adminCategory.updateCategory(req.auth!.userId, String(req.params.id), req.requestId, req.body) });
export const setCategoryActive: RequestHandler = async (req, res) => res.json({ data: await adminCategory.setCategoryActive(req.auth!.userId, String(req.params.id), req.requestId, req.body.isActive) });
export const deleteCategory: RequestHandler = async (req, res) => res.json({ data: await adminCategory.deleteCategory(req.auth!.userId, String(req.params.id), req.requestId) });
export const abandonedCarts: RequestHandler = async (req, res) => res.json({ data: await admin.abandonedCarts(req.auth!.userId) });
export const reminderOpened: RequestHandler = async (req, res) => res.json({ data: await admin.reminderOpened(req.auth!.userId, String(req.params.id), req.requestId) });
export const applications: RequestHandler = async (req, res) => res.json({ data: await admin.applications(req.auth!.userId) });
export const applicationDocument: RequestHandler = async (req, res) => res.json({ data: await admin.applicationDocumentUrl(req.auth!.userId, String(req.params.applicationId), String(req.params.documentId)) });
export const moderate: RequestHandler = async (req, res) => res.json({ data: await admin.moderate(req.auth!.userId, req.requestId, String(req.params.id), req.body.status as ModerationStatus, req.body.reason) });
export const productsForModeration: RequestHandler = async (req, res) => res.json({ data: await admin.productsForModeration(req.auth!.userId) });
export const taxProducts: RequestHandler = async (req, res) => res.json({ data: await admin.taxProducts(req.auth!.userId) });
export const updateProductTax: RequestHandler = async (req, res) => res.json({ data: await admin.updateProductTax(req.auth!.userId, req.requestId, String(req.params.id), req.body) });
export const moderateProduct: RequestHandler = async (req, res) => res.json({ data: await admin.moderateProduct(req.auth!.userId, req.requestId, String(req.params.id), req.body.decision, req.body.reason) });
export const access: RequestHandler = async (req,res)=>res.json({data:await admin.adminAccess(req.auth!.userId)});
export const overview: RequestHandler = async (req,res)=>res.json({data:await admin.overview(req.auth!.userId)});
export const orders: RequestHandler = async (req,res)=>res.json({data:await admin.adminOrders(req.auth!.userId,req.query)});
export const correctOrderStatus: RequestHandler = async (req,res)=>res.json({data:await admin.correctOrderStatus(req.auth!.userId,req.requestId,String(req.params.id),req.body.status as FulfillmentStatus,req.body.reason)});
export const payouts: RequestHandler = async (req,res)=>res.json({data:await admin.payouts(req.auth!.userId, req.query)});
export const processPayoutRequest: RequestHandler = async (req,res)=>res.json({data:await adminPayout.processPayoutRequest(req.auth!.userId, req.requestId, String(req.params.id))});
export const completePayoutRequest: RequestHandler = async (req,res)=>res.json({data:await adminPayout.completePayoutRequest(req.auth!.userId, req.requestId, String(req.params.id), req.body.settlementReference)});
export const rejectPayoutRequest: RequestHandler = async (req,res)=>res.json({data:await adminPayout.rejectPayoutRequest(req.auth!.userId, req.requestId, String(req.params.id), req.body.reason)});
export const notifications: RequestHandler = async (req,res)=>res.json({data:await admin.notifications(req.auth!.userId)});
export const markNotification: RequestHandler = async (req,res)=>res.json({data:await admin.markNotification(req.auth!.userId,String(req.params.id))});
export const markAllNotifications: RequestHandler = async (req,res)=>res.json({data:await admin.markAllNotifications(req.auth!.userId)});
export const team: RequestHandler = async (req,res)=>res.json({data:await admin.team(req.auth!.userId)});
export const updateTeamMember: RequestHandler = async (req,res)=>res.json({data:await admin.updateTeamMember(req.auth!.userId,String(req.params.id),{...req.body,role:req.body.role as AdminTeamRole|undefined},req.requestId)});

// --- Customer directory + payment attempts -------------------------------
export const customers: RequestHandler = async (req, res) => res.json({ data: await adminCustomer.customers(req.auth!.userId, req.query) });
export const customer: RequestHandler = async (req, res) => res.json({ data: await adminCustomer.customer(req.auth!.userId, String(req.params.id)) });
export const revokeCustomerSessions: RequestHandler = async (req, res) => res.json({ data: await adminCustomer.revokeCustomerSessions(req.auth!.userId, req.requestId, String(req.params.id)) });
export const transactions: RequestHandler = async (req, res) => res.json({ data: await adminTransaction.transactions(req.auth!.userId, req.query) });
export const auditLog: RequestHandler = async (req, res) => res.json({ data: await adminAudit.auditLog(req.auth!.userId, req.query) });
export const auditFilters: RequestHandler = async (req, res) => res.json({ data: await adminAudit.auditFilters(req.auth!.userId) });
export const reviews: RequestHandler = async (req, res) => res.json({ data: await adminReview.reviews(req.auth!.userId, req.query) });
export const reviewCounts: RequestHandler = async (req, res) => res.json({ data: await adminReview.reviewCounts(req.auth!.userId) });
export const setReviewHidden: RequestHandler = async (req, res) => res.json({ data: await adminReview.setReviewHidden(req.auth!.userId, String(req.params.id), Boolean(req.body.hidden), req.body.reason, req.requestId) });
export const dismissReviewReports: RequestHandler = async (req, res) => res.json({ data: await adminReview.dismissReports(req.auth!.userId, String(req.params.id), req.requestId) });
export const coupons: RequestHandler = async (req, res) => res.json({ data: await adminCoupon.coupons(req.auth!.userId, req.query) });
export const createCoupon: RequestHandler = async (req, res) => res.status(201).json({ data: await adminCoupon.createCoupon(req.auth!.userId, req.requestId, req.body) });
export const updateCoupon: RequestHandler = async (req, res) => res.json({ data: await adminCoupon.updateCoupon(req.auth!.userId, String(req.params.id), req.requestId, req.body) });
export const deleteCoupon: RequestHandler = async (req, res) => res.json({ data: await adminCoupon.deleteCoupon(req.auth!.userId, String(req.params.id), req.requestId) });
export const influencers: RequestHandler = async (req, res) => res.json({ data: await influencerCommission.influencers(req.auth!.userId) });
export const createInfluencer: RequestHandler = async (req, res) => res.status(201).json({ data: await influencerCommission.saveInfluencer(req.auth!.userId, req.requestId, req.body) });
export const updateInfluencer: RequestHandler = async (req, res) => res.json({ data: await influencerCommission.saveInfluencer(req.auth!.userId, req.requestId, { ...req.body, id: String(req.params.id) }) });
export const influencerCommissions: RequestHandler = async (req, res) => res.json({ data: await influencerCommission.commissionReport(req.auth!.userId, req.query) });
export const recordInfluencerRefund: RequestHandler = async (req, res) => res.status(201).json({ data: await influencerCommission.recordRefund(req.auth!.userId, req.requestId, String(req.params.vendorOrderId), req.body.amount, req.body.requestKey) });
export const settleInfluencerCommission: RequestHandler = async (req, res) => res.status(201).json({ data: await influencerCommission.settleCommission(req.auth!.userId, req.requestId, req.body.influencerId, req.body.amount, req.body.reference, req.body.requestKey) });
export const transaction: RequestHandler = async (req, res) => res.json({ data: await adminTransaction.transaction(req.auth!.userId, String(req.params.id)) });
export const createTeamMember: RequestHandler = async (req, res) => res.status(201).json({ data: await admin.createTeamMember(req.auth!.userId, req.requestId, { email: req.body.email, role: req.body.role as AdminTeamRole }) });
export const removeTeamMember: RequestHandler = async (req, res) => res.json({ data: await admin.removeTeamMember(req.auth!.userId, req.requestId, String(req.params.id)) });
export const permissionMatrix: RequestHandler = async (req, res) => res.json({ data: await admin.readPermissionMatrix(req.auth!.userId) });
export const setRolePermissions: RequestHandler = async (req, res) => res.json({ data: await admin.setRolePermissions(req.auth!.userId, req.requestId, req.body.role as AdminTeamRole, req.body.permissions) });
export const homepageVideo: RequestHandler = async (req, res) => res.json({ data: await adminHomepageVideo.homepageVideoForAdmin(req.auth!.userId) });
export const presignHomepageVideo: RequestHandler = async (req, res) => res.status(201).json({ data: await adminHomepageVideo.presignHomepageVideo(req.auth!.userId, req.body) });
export const updateHomepageVideo: RequestHandler = async (req, res) => res.json({ data: await adminHomepageVideo.updateHomepageVideo(req.auth!.userId, req.requestId, req.body) });
export const endorsements: RequestHandler = async (req, res) => res.json({ data: await featuredEndorsement.listAdminEndorsements(req.auth!.userId) });
export const createEndorsement: RequestHandler = async (req, res) => res.status(201).json({ data: await featuredEndorsement.createEndorsement(req.auth!.userId, req.requestId, req.body) });
export const updateEndorsement: RequestHandler = async (req, res) => res.json({ data: await featuredEndorsement.updateEndorsement(req.auth!.userId, String(req.params.id), req.requestId, req.body) });
export const publishEndorsement: RequestHandler = async (req, res) => res.json({ data: await featuredEndorsement.publishEndorsement(req.auth!.userId, String(req.params.id), req.requestId, req.body) });
export const unpublishEndorsement: RequestHandler = async (req, res) => res.json({ data: await featuredEndorsement.unpublishEndorsement(req.auth!.userId, String(req.params.id), req.requestId) });
export const archiveEndorsement: RequestHandler = async (req, res) => res.json({ data: await featuredEndorsement.archiveEndorsement(req.auth!.userId, String(req.params.id), req.requestId) });
export const presignEndorsementUpload: RequestHandler = async (req, res) => res.status(201).json({ data: await featuredEndorsement.presignEndorsementUpload(req.auth!.userId, req.body) });
