import type { RequestHandler } from 'express';
import { VerificationStatus } from '../generated/prisma/client.js';
import { prisma } from '../db/prisma.js';
import { ApiError } from '../utils/api-error.js';

export const categories: RequestHandler = async (_req, res) => res.json({ data: await prisma.category.findMany({ where: { isActive: true }, orderBy: { name: 'asc' } }) });
export const districts: RequestHandler = async (_req, res) => res.json({ data: ['BOKARO','CHATRA','DEOGHAR','DHANBAD','DUMKA','EAST_SINGHBHUM','GARHWA','GIRIDIH','GODDA','GUMLA','HAZARIBAGH','JAMTARA','KHUNTI','KODERMA','LATEHAR','LOHARDAGA','PAKUR','PALAMU','RAMGARH','RANCHI','SAHEBGANJ','SARAIKELA_KHARSAWAN','SIMDEGA','WEST_SINGHBHUM'] });
export const haats: RequestHandler = async (_req, res) => { const now = new Date(); res.json({ data: await prisma.weeklyHaat.findMany({ where: { isEnabled: true }, include: { overrides: { where: { enabled: true, liveFrom: { lte: now }, liveUntil: { gt: now } } } }, orderBy: [{ day: 'asc' }, { name: 'asc' }] }) }); };
export const product: RequestHandler = async (req, res) => { const item = await prisma.product.findFirst({ where: { OR: [{ id: String(req.params.id) }, { slug: String(req.params.id) }], isPublished: true, vendor: { verificationStatus: VerificationStatus.VERIFIED } }, include: { variants: { where: { isActive: true }, orderBy: { price: 'asc' } }, category: true, vendor: { select: { id: true, businessName: true, shgGroupName: true, district: true } }, weeklyHaat: true, media: { orderBy: [{ isCover: 'desc' }, { sortOrder: 'asc' }], select: { id: true, url: true, altText: true, isCover: true, sortOrder: true, width: true, height: true } } } }); if (!item) throw new ApiError(404, 'Product was not found.', 'PRODUCT_NOT_FOUND'); const { ratingFor } = await import('../services/review.service.js'); res.json({ data: { ...item, rating: await ratingFor(item.id) } }); };
