export const openApiDocument = {
  openapi: '3.1.0',
  info: { title: 'JoharHaat Marketplace API', version: '1.1.0', description: 'Customer, vendor and admin API for Jharkhand’s weekly marketplace.' },
  servers: [{ url: '/api/v1' }],
  components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } }, schemas: { Error: { type: 'object', properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' }, requestId: { type: 'string' } }, required: ['code','message','requestId'] } } } } },
  paths: {
    '/auth/register': { post: { summary: 'Register a customer account', tags: ['Auth'] } },
    '/auth/login': { post: { summary: 'Sign in with email and password', tags: ['Auth'] } },
    '/auth/refresh': { post: { summary: 'Rotate refresh session', tags: ['Auth'] } },
    '/auth/forgot-password': { post: { summary: 'Queue a password reset email', tags: ['Auth'] } },
    '/auth/reset-password': { post: { summary: 'Reset password with a single-use token', tags: ['Auth'] } },
    '/products/search': { get: { summary: 'Search available products', tags: ['Catalog'] } },
    '/categories': { get: { summary: 'List active storefront categories in display order', tags: ['Catalog'] } },
    '/homepage-video': { get: { summary: 'Read the enabled homepage brand video, if configured', tags: ['Catalog'] } },
    '/checkout': { post: { summary: 'Create a multi-vendor order transactionally', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/checkout/quote': { post: { summary: 'Validate cart and coupon, then return tax-inclusive totals for the selected delivery address', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/delivery/pincodes/{postalCode}': { get: { summary: 'Resolve a delivery PIN to its state, district, serviceability and fee', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/cart': { get: { summary: 'Get active cart', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/cart/items': { delete: { summary: 'Clear all items from the active cart atomically', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/payments/intents': { post: { summary: 'Create or replay a payment intent', tags: ['Payments'], security: [{ bearerAuth: [] }] } },
    '/payments/intents/{id}/verify': { post: { summary: 'Verify a Razorpay checkout signature and provider state', tags: ['Payments'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/payments/razorpay/webhook': { post: { summary: 'Receive signed Razorpay payment events', tags: ['Payments'] } },
    '/webhooks/resend': { post: { summary: 'Receive signed Resend delivery events', tags: ['Email'] } },
    '/payments/orders/{orderId}/state': { get: { summary: 'Read reload-safe order payment and reservation state', tags: ['Payments'], security: [{ bearerAuth: [] }], parameters: [{ name: 'orderId', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/orders': { get: { summary: 'List customer orders', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/vendor/dashboard': { get: { summary: 'Get vendor operational dashboard', tags: ['Vendor'], security: [{ bearerAuth: [] }] } },
    '/vendor/products': { post: { summary: 'Create a physical product for General Marketplace or an optional enabled Haat', tags: ['Vendor'], security: [{ bearerAuth: [] }] } },
    '/vendor/product-drafts': { get: { summary: 'List resumable vendor product drafts', tags: ['Vendor'], security: [{ bearerAuth: [] }] }, post: { summary: 'Create a partial vendor product draft', tags: ['Vendor'], security: [{ bearerAuth: [] }] } },
    '/vendor/product-drafts/{id}': { get: { summary: 'Read a vendor product draft', tags: ['Vendor'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] }, put: { summary: 'Update a partial vendor product draft', tags: ['Vendor'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] }, delete: { summary: 'Discard a vendor product draft', tags: ['Vendor'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/vendor/product-drafts/{id}/submit': { post: { summary: 'Validate a complete draft, create a product for review and remove the draft', tags: ['Vendor'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/admin/categories': { get: { summary: 'List all managed product categories', tags: ['Admin'], security: [{ bearerAuth: [] }] }, post: { summary: 'Create a product category', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/tax-products': { get: { summary: 'List products and their admin-managed HSN/GST configuration', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/settings': { get: { summary: 'Read delivery coverage settings', tags: ['Admin'], security: [{ bearerAuth: [] }] }, put: { summary: 'Configure free-delivery threshold and enable PIN pricing', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/pincodes': { get: { summary: 'Search delivery PIN coverage and fixed fees', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/pincodes/{postalCode}': { put: { summary: 'Update serviceability and fee for one imported PIN', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/pincodes/preview': { post: { summary: 'Validate a delivery PIN CSV without saving it', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/pincodes/import': { post: { summary: 'Atomically import a validated delivery PIN CSV', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/pincodes/export.csv': { get: { summary: 'Download the full delivery PIN list as CSV', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/delivery/pincodes/template.csv': { get: { summary: 'Download the delivery PIN CSV template', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/products/{id}/tax': { put: { summary: 'Set the verified HSN code and GST rate for a product', tags: ['Admin'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/admin/homepage-video': { get: { summary: 'Read homepage video settings', tags: ['Admin'], security: [{ bearerAuth: [] }] }, put: { summary: 'Replace, remove or toggle the homepage video', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/homepage-video/uploads/presign': { post: { summary: 'Create an authorized S3 upload for the homepage video', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/categories/{id}': { put: { summary: 'Update product category copy, order and featured state', tags: ['Admin'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] }, delete: { summary: 'Delete a product category with no assigned products', tags: ['Admin'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/admin/categories/{id}/active': { patch: { summary: 'Activate or deactivate a product category', tags: ['Admin'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/admin/analytics': { get: { summary: 'Get marketplace analytics', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
  },
} as const;
