export const openApiDocument = {
  openapi: '3.1.0',
  info: { title: 'JoharHaat Marketplace API', version: '1.1.0', description: 'Customer, vendor and admin API for Jharkhand’s weekly marketplace.' },
  servers: [{ url: '/api/v1' }],
  components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } }, schemas: { Error: { type: 'object', properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' }, requestId: { type: 'string' } }, required: ['code','message','requestId'] } } } } },
  paths: {
    '/auth/register': { post: { summary: 'Register a customer account', tags: ['Auth'] } },
    '/auth/login': { post: { summary: 'Sign in with email and password', tags: ['Auth'] } },
    '/auth/refresh': { post: { summary: 'Rotate refresh session', tags: ['Auth'] } },
    '/auth/forgot-password': { post: { summary: 'Queue a password reset email', tags: ['Auth'] } },
    '/auth/reset-password': { post: { summary: 'Reset password with a single-use token', tags: ['Auth'] } },
    '/products/search': { get: { summary: 'Search available products', tags: ['Catalog'] } },
    '/categories': { get: { summary: 'List active storefront categories in display order', tags: ['Catalog'] } },
    '/checkout': { post: { summary: 'Create a multi-vendor order transactionally', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/checkout/quote': { post: { summary: 'Validate cart, coupon, stock and authoritative totals', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/cart': { get: { summary: 'Get active cart', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/cart/items': { delete: { summary: 'Clear all items from the active cart atomically', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/payments/intents': { post: { summary: 'Create or replay a payment intent', tags: ['Payments'], security: [{ bearerAuth: [] }] } },
    '/payments/intents/{id}/verify': { post: { summary: 'Verify a Razorpay checkout signature and provider state', tags: ['Payments'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/payments/razorpay/webhook': { post: { summary: 'Receive signed Razorpay payment events', tags: ['Payments'] } },
    '/webhooks/resend': { post: { summary: 'Receive signed Resend delivery events', tags: ['Email'] } },
    '/payments/orders/{orderId}/state': { get: { summary: 'Read reload-safe order payment and reservation state', tags: ['Payments'], security: [{ bearerAuth: [] }], parameters: [{ name: 'orderId', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/orders': { get: { summary: 'List customer orders', tags: ['Commerce'], security: [{ bearerAuth: [] }] } },
    '/vendor/dashboard': { get: { summary: 'Get vendor operational dashboard', tags: ['Vendor'], security: [{ bearerAuth: [] }] } },
    '/vendor/products': { post: { summary: 'Create a physical product for General Marketplace or an optional enabled Haat', tags: ['Vendor'], security: [{ bearerAuth: [] }] } },
    '/admin/categories': { get: { summary: 'List all managed product categories', tags: ['Admin'], security: [{ bearerAuth: [] }] }, post: { summary: 'Create a product category', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
    '/admin/categories/{id}': { put: { summary: 'Update product category copy, order and featured state', tags: ['Admin'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/admin/categories/{id}/active': { patch: { summary: 'Activate or deactivate a product category', tags: ['Admin'], security: [{ bearerAuth: [] }], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }] } },
    '/admin/analytics': { get: { summary: 'Get marketplace analytics', tags: ['Admin'], security: [{ bearerAuth: [] }] } },
  },
} as const;
